name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "minor:"
        format: "${major}.${minor}.${patch}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker Image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t benjacifre/docker-graphql:$VERSION .
        docker build -t benjacifre/docker-graphql:latest .

    - name: Push Docker Image
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push benjacifre/docker-graphql:$VERSION
        docker push benjacifre/docker-graphql:latest
